---
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=${TIME_ZONE}
       ports:
            - 5055:5055
       volumes:
            - ${JELLYSEER_CONFIG}:/app/config
       restart: unless-stopped
       