---
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=America/New_York
       ports:
            - 5055:5055
       volumes:
            - /home/alex/docker/ContainerData/jellyseer/config:/app/config
       restart: unless-stopped
       