--- 
networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:${SQLPORT:-3306}
      - GITEA__database__NAME=${SQL_DB}
      - GITEA__database__USER=${SQL_USER}
      - GITEA__database__PASSWD=${SQL_PW}
    restart: always
    networks:
      - gitea
    volumes:
      - ${GITEA_DATA_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_PORT:-3000}:3000"
      - "${GITEA_SSH_PORT:-2234}:22"
    depends_on:
      - db
 
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PW}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PW}
      - MYSQL_DATABASE=${SQL_DB}
    networks:
      - gitea
    volumes:
      - ${SQL_DB_LOCATION}:/var/lib/mysql
      
#env_file:
#  - gitea.env