---
services:
  #comment out any services you don't plan to use

  # Portainer = GUI to manage containers
  #  portainer:
  #    image: portainer/portainer-ce
  #    container_name: portainer
  #    ports:
  #      - ${PORTAINER_PORT:-9000}:9000
  #    volumes:
  #      - /etc/localtime:/etc/localtime:ro
  #      - /var/run/docker.sock:/var/run/docker.sock:ro
  #      - ${PORTAINER_CONFIG}:/data
  #   restart: unless-stopped

#for local and/or cloud backup 
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - CLI_ARGS= #optional
    volumes:
      - ${DUPLICATI_CONFIG}:/config
      - ${BACKUP_DESTINATION}:/backups
      - ${SOURCE_DIRECTORY}:/source
    ports:
      - ${DUPLICATI_PORT:-8200}:8200
    restart: unless-stopped

#ftp client
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${FILEZILLA_CONFIG}:/config
      - ${STORAGE_PATH}:/Storage
    ports:
      - ${FILEZILLA_PORT:-3300}:3000
    restart: unless-stopped

#sync folders between multiple computers
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${RESILIO_SYNC_CONFIG}:/config
      - ${STORAGE_PATH}:/storage
    ports:
      - ${RESILIOSYNC_PORT:-8880}:8888
    restart: unless-stopped

#for cloud backup, subscription required
#follow https://github.com/JonathanTreffler/backblaze-personal-wine-container for setup instructions for backblaze container (below)
  backblaze-personal-wine:
    image: tessypowder/backblaze-personal-wine:latest
    container_name: backblaze  
    init: true
    volumes:
      - ${DATA_TO_BACKUP}:/drive_d/
      - ${BACKBLAZE_CONFIG_DATA}:/config/
    ports:
      - ${BACKBLAZE_PORT:-8080}:5800
    restart: unless-stopped

#youtube-dl with a web interface
  metube:
    image: ghcr.io/alexta69/metube
    container_name: youtube-dl
    restart: unless-stopped
    ports:
      - ${YOUTUBEDL_PORT:-6061}:8081
    volumes:
      - ${YOUTUBEDL_DOWNLOADS}:/downloads
  
# uncomment lines below to deploy with docker-compose        
#env_file:
#  - tools.env